{
 "title": "DISSEM",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "RAM used memory(bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "nv_cpu_memory_used_bytes", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "nv_cpu_utilization", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Request Failure",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nv_inference_request_failure", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "Request Success",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nv_inference_request_success", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "Inference count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nv_inference_count", "legendFormat": "{{model}}" }
   ]
  }
 ]
}