apiVersion: v1
kind: Secret
metadata:
  name: minio-kserve-secret
  namespace: observability
  annotations:
     serving.kserve.io/s3-endpoint: "ip:port"
     serving.kserve.io/s3-usehttps: "0"
     serving.kserve.io/s3-useanoncredential: "false"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "..."
  AWS_SECRET_ACCESS_KEY: "..."
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-minio-kserve
  namespace: observability
secrets:
- name: minio-kserve-secret
