apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-mlflow
  labels:
    app: minio-mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-mlflow
  template:
    metadata:
      labels:
        app: minio-mlflow
    spec:
      containers:
      - name: minio-mlflow
        image: quay.io/minio/minio:latest
        command:
        - /bin/bash
        - -c
        args: 
        - minio server /data --console-address :9001

        ports:
        - containerPort: 9000
        - containerPort: 9001
        imagePullPolicy: Always
        env:
        - name: MINIO_ROOT_USER
          value: "minio"
        - name: MINIO_ROOT_PASSWORD
          value: "minio123"
        volumeMounts:
        - name: minio-storage
          mountPath: "/data"
      volumes:
      - name: minio-storage
        persistentVolumeClaim:
          claimName: minio-pvc-mlflow
---

apiVersion: v1
kind: Service
metadata:
  name: minio-mlflow
spec:
  selector:
    app: minio-mlflow
  ports:
  - name: http
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
  type: ClusterIP

