apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc-mlflow
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
